# docker-compose -f .\docker-compose.yml up --build --detach
version: '2'
services:
  hello-world-nodejs:
    image: ethzero/helloworld:latest
    # build:
    #   context: ./node_src
    ports:
      - 8080:8080
    networks: 
      hello_world_network:
        ipv4_address: 172.25.0.2

  hello-world-redis:
    container_name: hello-world-redis
    image: redis
    ports:
      - 6379:6379
    networks: 
      hello_world_network:
        ipv4_address: 172.25.0.3

  redis-commander:
    image: rediscommander/redis-commander
    ports: 
      - 8081:8081
    environment: 
      - REDIS_HOSTS=172.25.0.3
    networks: 
      hello_world_network:
        ipv4_address: 172.25.0.4

networks:
  hello_world_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
